# vim:ft=kitty

## name:     rxyhn
## author:   botmanu

# The basic colors
foreground            #D9D7D6
background            #061115
selection_foreground  #061115
selection_background  #78B892

# Cursor colors
cursor                #D9D7D6
cursor_text_color     #061115

# URL underline color when hovering with mouse
url_color             #6791C9

# Kitty window border colors
active_border_color   #78B892
inactive_border_color #222d31
bell_border_color     #ecd28b

# Tab bar colors
active_tab_foreground   #061115
active_tab_background   #78B892
inactive_tab_foreground #D9D7D6
inactive_tab_background #0C171B
tab_bar_background      #061115

# The 16 terminal colors

# black
color0  #061115
color8  #313c40

# red
color1  #DF5B61
color9  #EE6A70

# green
color2  #78B892
color10 #8CD7AA

# yellow
color3  #ecd28b
color11 #f6dc95

# blue
color4  #6791C9
color12 #79AAEB

# magenta (purple)
color5  #C488EC
color13 #BC83E3

# cyan (aqua)
color6  #7ACFE4
color14 #67AFC1

# white (grey)
color7  #D9D7D6
color15 #EDEBEA
